# This file was automatically generated by SWIG (http://www.swig.org).
# Version 1.3.36
#
# Don't modify this file, modify the SWIG interface instead.
# This file is compatible with both classic and new-style classes.

import _pynklevel
import new
new_instancemethod = new.instancemethod
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'PySwigObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static) or hasattr(self,name):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError,name

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

import types
try:
    _object = types.ObjectType
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0
del types


class LevelerException:
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, LevelerException, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, LevelerException, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _pynklevel.new_LevelerException(*args)
        try: self.this.append(this)
        except: self.this = this
    def what(*args): return _pynklevel.LevelerException_what(*args)
    def whatCode(*args): return _pynklevel.LevelerException_whatCode(*args)
    __swig_destroy__ = _pynklevel.delete_LevelerException
    __del__ = lambda self : None;
LevelerException_swigregister = _pynklevel.LevelerException_swigregister
LevelerException_swigregister(LevelerException)

class Printer(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Printer, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Printer, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _pynklevel.new_Printer(*args)
        try: self.this.append(this)
        except: self.this = this
    def GetTanks(*args): return _pynklevel.Printer_GetTanks(*args)
    def GetTankLevel(*args): return _pynklevel.Printer_GetTankLevel(*args)
    def Name(*args): return _pynklevel.Printer_Name(*args)
    def TankCount(*args): return _pynklevel.Printer_TankCount(*args)
    def GetTankType(*args): return _pynklevel.Printer_GetTankType(*args)
    __swig_destroy__ = _pynklevel.delete_Printer
    __del__ = lambda self : None;
Printer_swigregister = _pynklevel.Printer_swigregister
Printer_swigregister(Printer)

getusbprinterlevels = _pynklevel.getusbprinterlevels


